### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by letrast** [timsutton/make-adobe-cc-license-pkg#2]
Tim,

This is just what I'm looking for (in addition to the countless invaluable, lifesaving, other contributions you've made to this industry!).

However, when I run the tool, I get the following errors:

```
** Found serial number (enterprise) license type in prov.xml
** Found LEID 'V7{}CreativeCloudEnt-1.0-Mac-GM' in prov.xml
** Extracted version 9.0.0.26 from adobe_prtk Info.plist section
Traceback (most recent call last):
  File "/Users/letrast/Desktop/make-adobe-cc-license-pkg", line 241, in <module>
    main()
  File "/Users/letrast/Desktop/make-adobe-cc-license-pkg", line 186, in main
    postinstall_template = Template(open(os.path.join(templates_dir, 'postinstall')).read())
IOError: [Errno 2] No such file or directory: '/Users/letrast/Desktop/script_templates/postinstall'
```

Any thoughts?

**Comment by timsutton** [comment]
Hi @letrast, it looks like you may be running the tool as a standalone file, since it can't locate the `script_templates` dir, and you're working in your `Desktop` dir. Try doing a full clone of this repo and running the tool from there, if you aren't already.

**Comment by letrast** [comment]
Thanks, that was it.  I'm still pretty new to GitHub so this was helpful for the future too.

**Comment by timsutton** [comment]
No problem. Thanks for your comments!
