### ISSUE TITLE
CC 2017?

### ISSUE THREAD

**Issue by majorsl** [timsutton/make-adobe-cc-license-pkg#3]
Tim, does this work on the new CC 2017?  We're having issues even scripting the AdobeSerializer tool which worked in the past. AdobeSerializer's cli is popping up a GUI user/pass for an administrator even though we are administrators. We didn't observe this in the past which is why licensing is failing for us since with Munki a console user isn't logged in when it's run.

I stumbled across this which seems like a natural fit for us rather then trying to get our custom serialization pkg working again.

**Comment by timsutton** [comment]
I don't see why it wouldn't, however I haven't yet needed to test it, as I have a license pkg built with a license file from June, and that license file _seems_ to cover at least Photoshop CC 2017. I'm not sure whether that entitlement extends to all the other apps released today as well.

I'm not convinced `AdobeSerializer` was ever tested in typical mass deployment scenarios, although I feel the same might be said for most Adobe installer tools.

**Comment by majorsl** [comment]
We're having an awful time with 2017. Even serialized packages are failing on some units and successful on others. We've not had success with this, it usually fails with a 21 or sometimes 22 error:

```
'21': "Unable to update PCF/SLCache",
'22': "Unable to open a PCF/SLCache session",
```

Although my Google-fu is failing me and I'm not sure exactly what that MEANS.

Manually running the AdobeSerializer yields a 100% success rate for us, but it is tedious and annoying and shouldn't be necessary. :)

**Comment by timsutton** [comment]
Do you have an enterprise or teams-based license?

**Comment by majorsl** [comment]
Enterprise.

**Comment by timsutton** [comment]
Re-reading this - did you try this tool with your new license yet? Wasn't clear whether the reliability problems you're having are just from trying to automate `AdobeSerializer`.

**Comment by clburlison** [comment]
I just verified that this does work with a Named license of Photoshop 2017. After I installed PS2017 I launch and had the sign in for a trial. Closed the window. Ran the `make-adobe-cc-license-pkg` script:

``` bash
./make-adobe-cc-license-pkg /Users/clburlison/Desktop/adobe2017License  -o ~/Desktop/
```

Then installed the newly created `adobe2017License-2016.11.03.pkg` package. Launched PS2017 and the application is properly licensed. I'm using an Enterprise license over here.

**Comment by majorsl** [comment]
Okay! Sounds like it is me. Here's how I'm doing it, it could be I'm missing something.

1) Creative Cloud Packager, Create License Package.
2) Package Name AdobeCCLicense, save to Desktop
3) Enter Enterprise License Key, verifies successfully.
4) Says it was built successfully, build log has one error I noted: "Failed to update the timestamps for Install pkg" - possible issue?
5) Testing resultant AdobeSerialization binary does correctly license Named installs.
6) ./make-adobe-cc-license-pkg /Users/majorsl/Desktop/AdobeCCLicense -o ~/Desktop
*\* Found serial number (enterprise) license type in prov.xml
*\* Found LEID 'V7{}CreativeCloudEnt-1.0-Mac-GM' in prov.xml
*\* Extracted version 10.0.0.36 from adobe_prtk Info.plist section
*\* Wrote uninstall script to /Users/majorsl/Desktop/AdobeCCLicense-2016.11.03.uninstall
pkgbuild: Inferring bundle components from contents of /var/folders/wr/t_ssvmcd5k177t9m91l4wtrjl39b77/T/tmpAKsrCj
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to /Users/majorsl/Desktop/AdobeCCLicense-2016.11.03.pkg
*\* Built package at /Users/majorsl/Desktop/AdobeCCLicense-2016.11.03.pkg
*\* Done.

Does that all look good? If so, I'm going to try it with a package downloaded directly from the portal with the updates turned off (we want to manage that).  I typically build them with CCP with the options we need.

**Comment by timsutton** [comment]
That all looks good. But what I thought from the beginning was that you'd tried _installing_ this package to license a client, instead of using Adobe's provided `AdobeSerialization` tool.

**Comment by majorsl** [comment]
I've been testing since the above. On a freshly imaged machine with no Adobe products installed, and installing a Named package, it all works _perfectly_. The issue seems to be when we try to license products that have also had serialized packages previously installed.  The package install (AdobeCCLicense-2016.11.03.pkg) will fail.

Probably a bit off topic, but would the uninstall script be able to remove any of this.  I think we want to convert to Named packages and use this tool to serialize them, but I'm now trying to figure out a way to transition between the two.

**Comment by timsutton** [comment]
I'd strongly encourage you to send problem reports to Karl Gibson at Adobe: kagibson@adobe.com. He'll probably ask you to provide logs gathered with the [Log Collector Tool](https://helpx.adobe.com/creative-cloud/kb/cc-log-collector.html), but you should also try and isolate a specific set of install sequences so you can describe to him the series of steps you've taken and when the failures happen.

**Comment by majorsl** [comment]
Thanks for the help!
